[package]
name = "reiha"
version = "1.1.1"
authors = ["bk <boris.komarov@proton.me>"]
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
clearscreen = "4.0.1"
dirs = "6.0.0"
macroquad = "0.4.14"
macroquad-canvas = "0.4.1"
