[package]
name = "reiha"
version = "0.1.0"
authors = ["bk <boris.komarov@proton.me>"]
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
clearscreen = "4.0.1"
macroquad = "0.4.14"
macroquad-canvas = "0.4.1"
